---
deployment:
  tasks:
    - echo "Installing dependencies..." | tee -a ~/deploy.log
    - /opt/cpanel/ea-nodejs18/bin/npm install 2>&1 | tee -a ~/deploy.log
    - echo "Building Vite app..." | tee -a ~/deploy.log
    - /opt/cpanel/ea-nodejs18/bin/npm run build 2>&1 | tee -a ~/deploy.log
    - echo "Listing dist/ contents..." | tee -a ~/deploy.log
    - ls -la dist >> ~/deploy.log
    - echo "Deploying build to public_html..." | tee -a ~/deploy.log
    - /bin/rm -rf /home/rankandrentniche/public_html/*
    - /bin/cp -R dist/* /home/rankandrentniche/public_html/
