deployment:
  tasks:
    - /bin/echo "Installing dependencies..."
    - /usr/bin/npm install
    - /bin/echo "Building Vite app..."
    - /usr/bin/npm run build
    - /bin/echo "Cleaning public_html..."
    - /bin/rm -rf /home/rankandrentniche/public_html/*
    - /bin/echo "Copying build output..."
    - /bin/cp -R dist/. /home/rankandrentniche/public_html/
    - /bin/echo "Contents of public_html after copy:"
    - /bin/ls -la /home/rankandrentniche/public_html/
    - /bin/echo "✅ Deployment complete."
