---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rankandrentniche/niche-finder/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
